name: build Gmeek

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

env:
  GITHUB_NAME: duckqing
  GITHUB_EMAIL: 294977308@qq.com

jobs:
  sync:
    name: Generate blog
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Clone source code
        run: |
          git clone https://github.com/Meekdai/Gmeek.git /opt/Gmeek

      - name: Install dependencies
        run: |
          cd /opt/Gmeek
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate new html
        run: |
          cp config.json /opt/Gmeek/
          cd /opt/Gmeek
          cat config.json
          
          python Gmeek.py ${{ secrets.meblog }} ${{ github.repository }} --issue_number '${{ github.event.issue.number }}'
          cp -a /opt/Gmeek/docs/. /home/runner/work/duckqing.github.io/duckqing.github.io/
          ls
        
      - name: update html
        run: |
          ls
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -a -m '🎉auto update by action' || echo "nothing to commit"
          git push || echo "nothing to push"
        
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          personal_token: ${{ secrets.meblog }}
        
